In [14]:
# import numpy

import numpy as np
from scipy import sparse

### 1.1 Creating a Vector

In [3]:
vector_row = np.array([1, 2, 3])
vector_row

array([1, 2, 3])

In [4]:
vector_column = np.array([[1], [2], [3]])
vector_column

array([[1],
       [2],
       [3]])

### 1.2 Creating a 2D Array

In [13]:
matrix_obj = np.array([[1,2,3],[1,2,3],[1,2,3]])
matrix_obj

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### 1.3 Creating a Sparse Matrix

In [17]:
# create a matrix

mat = np.array([[0,0], [0,1], [3,0]])

# apply sparse function

matrix_sparse = sparse.csr_matrix(mat)

In [18]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [19]:
mat.shape

(3, 2)

In [20]:
mat.size

6

In [21]:
mat.ndim

2

### 1.6 Applying Operations to Elements

In [23]:
# creat a sample matrix

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
# create a function that adds 100 to something

add_100 = lambda x: x + 100

In [26]:
# create a vectorized function

vectorized_add_100 = np.vectorize(add_100)

In [27]:
# pass matrix to new function

vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [28]:
# and now the same result with broadcasting
# add 100 to all elements

matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

### 1.10 Transposing a Vector or Matrix

In [31]:
# transpose matrix using T(ranspose)

matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [35]:
# Transpose has no effect on a 1D array
# But it can flip row vectors to column, and vice versa

row_vector = np.array([[1,2,3,4,5,6]])
col_vector = row_vector.T

In [37]:
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [38]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### 1.11 Flattening a Matrix

In [39]:
# view the matrix object

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
# flatten the matrix using the flatten() method

matrix_flattened = matrix.flatten()
matrix_flattened

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1.12 Finding the Rank of a Matrix

In [48]:
# create example matrix

m = np.array([[1,4,1], [1,4,10], [1,4,15]])
m

array([[ 1,  4,  1],
       [ 1,  4, 10],
       [ 1,  4, 15]])

In [49]:
# return matrix rank

np.linalg.matrix_rank(m)

2

### 1.13 Calculating the Determinant of a Matrix

In [50]:
# view sample matrix

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
# return determinant of matrix

np.linalg.det(matrix)

-9.51619735392994e-16

### 1.14 Accessing the Diagonal of a Matrix

In [53]:
# view sample matrix

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
matrix.diagonal()

array([1, 5, 9])

In [55]:
# you can also get diagonal off of the main diagonal
# using the offset argument

matrix.diagonal(offset=1)

array([2, 6])

### 1.15 Calculating the Trace of a Matrix

In [56]:
# view sample matrix

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
# calculate trace using trace() method

matrix.trace()

15

In [58]:
# the trace is the sum of the numbers on the diagonal

sum(matrix.diagonal()) == matrix.trace()

True

### 1.16 Finding Eigenvalues and Eigenvectors

In [60]:
# create sample matrix

mat = np.array([[1, -1, 3], [1, 1, 6], [3, 8, 9]])
mat

array([[ 1, -1,  3],
       [ 1,  1,  6],
       [ 3,  8,  9]])

In [61]:
# calc eigenvalues and eigenvectors and unpack them

eigenvalues, eigenvectors = np.linalg.eig(mat)

In [62]:
# display eigenvalues --> stored as 1D array

eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [63]:
# display eigenvectors --> stored in a square matrix of
# the same dimensions as the orginal

eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

### 1.17 Calculating Dot Products

In [64]:
# create sample arrays

vect_a = np.array([1, 2, 3])
vect_b = np.array([4, 5, 6])

In [65]:
# calc using numpy's dot() function

np.dot(vect_a, vect_b)

32

In [66]:
# calc using shorthand function with @ operator

vect_a @ vect_b

32

In [67]:
# NOTE: If element-wise multiplication is required, use * operator

vect_a * vect_b

array([ 4, 10, 18])

### 1.20 Inverting a Matrix

In [69]:
# create a sample matrix

matrix = np.array([[1, 4], [2, 5]])
matrix

array([[1, 4],
       [2, 5]])

In [72]:
# calculate the inverse of the matrix

matrix_inv = np.linalg.inv(matrix)
matrix_inv

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [74]:
# confirm the inverse by calculating the dot product of matrix
# and its inverse.

matrix @ matrix_inv

array([[1., 0.],
       [0., 1.]])

In [77]:
# proof

id_2x2 = np.eye(2,2)

matrix @ matrix_inv == id_2x2

array([[ True,  True],
       [ True,  True]])

### 1.21 Generating Random Values

In [81]:
# set the random seed

np.random.seed(425)

In [89]:
# generate three random floats between 0 & 1

np.random.random(3)

array([0.68840183, 0.23849475, 0.01775733])

In [91]:
# scale up the values by multiplying by a scalar

values = np.random.random(9) * 100
values

array([27.51979372,  9.22038902, 50.56053543, 68.00073786, 24.60170442,
        7.90723311, 11.37904438, 96.93453471, 90.27311463])

In [95]:
# reshape the array into a matrix using reshape()

values.reshape(3,3)

array([[27.51979372,  9.22038902, 50.56053543],
       [68.00073786, 24.60170442,  7.90723311],
       [11.37904438, 96.93453471, 90.27311463]])

In [94]:
# generating random integers by specifying beginning and end of range
# and the number of values to generate

np.random.randint(0, 101, 10)

array([54,  6, 35, 67, 99, 60, 89,  3, 18, 60])

#### Generating numbers sampled randomly from a distribution:


In [96]:
# Five values from a normal dist with a mean of 50 and a stdev of 10

np.random.normal(50, 10, 5)

array([51.5960649 , 55.70619574, 47.02101325, 46.56505002, 48.19533816])

In [97]:
# Four values from a uniform dist >= 40 and < 60

np.random.uniform(40, 60, 4)

array([45.34550664, 45.81311817, 50.95049659, 46.30054339])